routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*admin route*/

Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');
Route::resource('type','TypeController');
Route::resource('subtype','SubTypeController');
Route::resource('student','StudentController');
Route::resource('parent','ParentController');
Route::resource('teacher','TeacherController');
Route::resource('staff','StaffController');
Route::resource('class','ClassController');
Route::resource('classroutine','ClassRoutineController');
Route::resource('exam','ExamController');
Route::resource('examschedule','StExamScheduleController');
Route::resource('subject','SubjectController');
Route::resource('expense','ExpenseController');
Route::resource('hostel','HostelController');
Route::resource('transport','TransportController');
Route::resource('message','MessageController');
Route::resource('notice','NoticeController');
Route::resource('attendance','AttendanceController');
});

/*author route*/

Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'author'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});

/*teacher route*/

Route::group(['as'=>'teacher.','prefix'=>'teacher','namespace'=>'teacher'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});

/*student route*/

Route::group(['as'=>'student.','prefix'=>'student','namespace'=>'student'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});


/*parent route*/

Route::group(['as'=>'parent.','prefix'=>'parent','namespace'=>'parent'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});


/*staff route*/

Route::group(['as'=>'staff.','prefix'=>'staff','namespace'=>'staff'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});

app/Http/Controllers/Admin/TypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Support\Str;
use Illuminate\Support\Arr;
use DB;
use App\Admin\TypeForm;
use Brian2694\Toastr\Facades\Toastr;

class TypeController extends Controller
{

    public function index()
    {
        $types = TypeForm::latest()->get();
        return view("admin.type.index",compact('types'));
    }

    public function create()
    {
        return view('admin.type.create');
    }

    public function store(Request $request)
    {
       $this->validate($request,[
        'type' => 'required'
       ]);

       $type = new TypeForm();
       $type->type = $request->type;
       $type->save();
       Toastr::success('Type Successfully Created!! : ', 'success');
       return redirect()->route('admin.type.index');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $type = TypeForm::find($id);
        return view('admin.type.edit',compact('type'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
        'type' => 'required'
        ]);

        $type = TypeForm::find($id);
        $type->type = $request->type;
        $type->save();
        Toastr::success('Type Successfully Updated!! : ', 'success');
        return redirect()->route('admin.type.index');
    }

    public function destroy($id)
    {
        TypeForm::find($id)->delete();
        Toastr::success('Type Successfully Deleted :)','Success');
        return redirect()->back();
    }
}

resources/views/admin/type/create.blade.php
@extends('sms.backend.app')

@section('sms-title')
Create Student | Admission Form Data
@endsection

@section('css')
<!-- Bootstrap Select Css -->
<link href="{{ asset('assets/sms') }}/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />

@endsection

@section('main-content')
  <div class="container-fluid">
<div class="block-header">

</div>

<!-- Vertical Layout -->
<div class="row clearfix">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="card">
<div class="header">

</div>
<div class="body">
    <form method="POST" action="{{ route('admin.type.store') }}">
    	@csrf
        <label for="email_address">Type</label>
        <div class="form-group">
            <div class="form-line">
               <input type="text" name="type" id="type" class="form-control" placeholder="Enter Type">
            </div>
        </div>

  <div class="row">
    <div class="col-md-4">
      <a href="{{ route('admin.type.index') }}" class="btn bg-amber btn-lg btn-block waves-effect">
      <i class="material-icons">arrow_back</i>
      <span>Back</span>
       </a> 
     </div>
    <div class="col-md-4">
    <button type="submit" class="btn bg-pink btn-lg btn-block waves-effect">
        <i class="material-icons">save</i>
       <span>Save</span>
    </button>  
    </div>
    <div class="col-md-4">
    <button type="submit" class="btn bg-blue btn-lg btn-block waves-effect">
        <i class="material-icons">clear</i>
       <span>Clear</span>
    </button>
    </div>
    </div>

    </form>
</div>
</div>
</div>
</div>
<!-- #END# Vertical Layout -->
</div>
@endsection

@section('js')
<!-- Custom Js -->
<script src="{{ asset('assets/sms') }}/js/pages/forms/basic-form-elements.js"></script>
@endsection

resources/views/admin/type/edit.blade.php
@extends('sms.backend.app')

@section('sms-title')
Create Student | Admission Form Data
@endsection

@section('css')
<!-- Bootstrap Select Css -->
<link href="{{ asset('assets/sms') }}/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />

@endsection

@section('main-content')
  <div class="container-fluid">
<div class="block-header">

</div>

<!-- Vertical Layout -->
<div class="row clearfix">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="card">
<div class="header">

</div>
<div class="body">
<form method="POST" action="{{ route('admin.type.update',$type->id) }}">
	@csrf
	  @method('put')
    <label for="email_address">Type</label>
    <div class="form-group">
        <div class="form-line">
           <input type="text" name="type" id="type" value="{{ $type->type }}" class="form-control" placeholder="Enter Type">
        </div>
    </div>
     <a href="{{ route('admin.type.index') }}" class="btn bg-amber btn-lg waves-effect">
        <i class="material-icons">arrow_back</i>
       <span>Back</span>
     </a>
     <button type="submit" class="btn bg-pink btn-lg waves-effect">
        <i class="material-icons">save</i>
       <span>Update</span>
    </button>
     <button type="submit" class="btn bg-blue btn-lg waves-effect">
        <i class="material-icons">clear</i>
       <span>Clear</span>
    </button>
</form>
</div>
</div>
</div>
</div>
<!-- #END# Vertical Layout -->
</div>
@endsection

@section('js')

  <!-- Custom Js -->
<script src="{{ asset('assets/sms') }}/js/pages/forms/basic-form-elements.js"></script>
@endsection

resources/views/admin/type/index.blade.php
@extends('sms.backend.app')

@section('sms-title')
All Student | Admission Form Data
@endsection

@section('css')

    <!-- JQuery DataTable Css -->
    <link href="{{ asset('assets/sms') }}/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">

@endsection

@section('main-content')
  <div class="container-fluid">
<div class="block-header">
   <a href="{{ route('admin.type.create') }}" class="btn btn-warning btn-lg waves-effect">
         <i class="material-icons">create</i>
         <span>Create</span>
    </a>
</div>
<!-- Exportable Table -->
<div class="row clearfix">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="card">
<div class="header">
<button class="btn bg-purple btn-lg waves-effect" type="button">All Types <span class="badge">{{ $types->count() }}</span></button>
</div>
<div class="body">
<div class="table-responsive">
<table class="table table-bordered table-striped table-hover dataTable js-exportable">
<thead>
    <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Action</th>
        <th>created_at</th>
        <th>updated_at</th>
    </tr>
</thead>
<tfoot>
     <tr>
        <th>ID</th>
        <th>Type</th>
        <th>created_at</th>
        <th>updated_at</th>
        <th>Action</th>

    </tr>
</tfoot>
<tbody>
@foreach($types as $key=>$type)
<tr>
    <td>{{ $key + 1 }}</td>
    <td>{{ $type->type }}</td>
    <td>{{ $type->created_at }}</td>
    <td>{{ $type->updated_at }}</td>
    <td>
     <a class="btn btn-primary" href=""><i class="material-icons">remove_red_eye</i></a>
     <a class="btn btn-success" href="{{ route('admin.type.edit', $type->id) }}"><i class="material-icons">edit</i></a> 
     <button class="btn btn-danger waves-effect" type="button" onclick="deleteType({{ $type->id }})">
        <i class="material-icons">delete</i>
    </button>
    <form id="delete-form-{{ $type->id }}" action="{{ route('admin.type.destroy',$type->id) }}" method="POST" style="display: none;">
        @csrf
          @method('DELETE')
    </form>
        
    </td>
</tr>
@endforeach
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<!-- #END# Exportable Table -->
        </div>
@endsection

@section('js')

    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

    <script src="{{ asset('assets/sms') }}/js/pages/tables/jquery-datatable.js"></script>
    <script src="{{ asset('js/sweetalert2.all.js') }}"></script>
     <!--<script src="https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>-->
     <script type="text/javascript">
        function deleteType(id) {
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false,
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-'+id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === swal.DismissReason.cancel
                ) {
                    swal(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                    )
                }
            })
        }
    </script>
@endsection