routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*admin route*/

Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');
Route::resource('type','TypeController');
Route::resource('subtype','SubTypeController');
Route::resource('student','StudentController');
Route::resource('parent','ParentController');
Route::resource('teacher','TeacherController');
Route::resource('staff','StaffController');
Route::resource('class','ClassController');
Route::resource('classroutine','ClassRoutineController');
Route::resource('exam','ExamController');
Route::resource('examschedule','StExamScheduleController');
Route::resource('subject','SubjectController');
Route::resource('expense','ExpenseController');
Route::resource('hostel','HostelController');
Route::resource('transport','TransportController');
Route::resource('message','MessageController');
Route::resource('notice','NoticeController');
Route::resource('attendance','AttendanceController');
});

/*author route*/

Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'author'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});

/*teacher route*/

Route::group(['as'=>'teacher.','prefix'=>'teacher','namespace'=>'teacher'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});

/*student route*/

Route::group(['as'=>'student.','prefix'=>'student','namespace'=>'student'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});


/*parent route*/

Route::group(['as'=>'parent.','prefix'=>'parent','namespace'=>'parent'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});


/*staff route*/

Route::group(['as'=>'staff.','prefix'=>'staff','namespace'=>'staff'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});

app/Http/Controllers/Admin/SubTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Support\Str;
use Illuminate\Support\Arr;
use DB;
use App\Admin\SubTypeForm;
use App\Admin\TypeForm;
use Brian2694\Toastr\Facades\Toastr;

class SubTypeController extends Controller
{
   public function index()
    {
        //$subtypes = SubTypeForm::latest()->get();
        
        $subtypes = DB::table('sub_type_forms')
                  ->join('type_forms','sub_type_forms.type_id','=','type_forms.id')
                  ->select('sub_type_forms.*','type_forms.type')
                  ->get();

        return view("admin.subtype.index", compact('subtypes'));
    }

    public function create()
    {
        $subtypes = TypeForm::select('id','type')->get();
        $types = TypeForm::all();
        return view('admin.subtype.create',compact('types','subtypes'));
    }

    public function store(Request $request)
    {
       $this->validate($request,[
        'subtype' => 'required'
       ]);

       $subtype = new SubTypeForm();
       $subtype->type_id = $request->type_id;
       $subtype->subtype = $request->subtype;
       $subtype->save();
       Toastr::success('Sub Type Successfully Created!! : ', 'success');
       return redirect()->route('admin.subtype.index');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $subtypes = TypeForm::select('id','type')->get();
        $subtypeform = SubTypeForm::find($id);
        return view('admin.subtype.edit',compact('subtypes','subtypeform'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
        'subtype' => 'required'
        ]);

       $subtype = SubTypeForm::find($id);

       $subtype->type_id = $request->type_id;
       $subtype->subtype = $request->subtype;
       $subtype->save();
       Toastr::success('Sub Type Successfully Updated!! : ', 'success');
       return redirect()->route('admin.subtype.index');
    }

    public function destroy($id)
    {
        SubTypeForm::find($id)->delete();
        Toastr::success('Sub Type Successfully Deleted!! : ', 'success');
        return redirect()->back();
    }
}

resources/views/admin/subtype/create.blade.php
@extends('sms.backend.app')

@section('sms-title')
Create Sub Types | Admission Form Data
@endsection

@section('css')
<!-- Bootstrap Select Css -->
<link href="{{ asset('assets/sms') }}/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />

@endsection

@section('main-content')
  <div class="container-fluid">
<div class="block-header">

</div>

<!-- Vertical Layout -->
<div class="row clearfix">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="card">
<div class="header">

</div>
<div class="body">
<form method="POST" action="{{ route('admin.subtype.store') }}">
	@csrf
	<div class="row clearfix">
    <div class="col-sm-6">
        <select name="type_id" class="form-control show-tick">
            <option value="">-- Please select --</option>
            @foreach($subtypes as $subtype)
            <option value="{{ $subtype->id }}">{{ $subtype->type }}</option>
            @endforeach
        </select>
    </div>
    <div class="col-sm-6">
    <label for="email_address">SubType</label>
    <div class="form-group">
        <div class="form-line">
           <input type="text" name="subtype" id="subtype" class="form-control" placeholder="Enter Type">
        </div>
    </div>
    </div>
  </div>

     <div class="row">
    <div class="col-md-4">
      <a href="{{ route('admin.subtype.index') }}" class="btn bg-amber btn-lg btn-block waves-effect">
      <i class="material-icons">arrow_back</i>
      <span>Back</span>
       </a> 
     </div>
    <div class="col-md-4">
    <button type="submit" class="btn bg-pink btn-lg btn-block waves-effect">
        <i class="material-icons">save</i>
       <span>Save</span>
    </button>  
    </div>
    <div class="col-md-4">
    <button type="submit" class="btn bg-blue btn-lg btn-block waves-effect">
        <i class="material-icons">clear</i>
       <span>Clear</span>
    </button>
    </div>
    </div>

</form>
</div>
</div>
</div>
</div>
<!-- #END# Vertical Layout -->
</div>
@endsection

@section('js')

<!-- Custom Js -->
<script src="{{ asset('assets/sms') }}/js/pages/forms/basic-form-elements.js"></script>
@endsection

resources/views/admin/subtype/edit.blade.php
@extends('sms.backend.app')

@section('sms-title')
Create Sub Types | Admission Form Data
@endsection

@section('css')
<!-- Bootstrap Select Css -->
<link href="{{ asset('assets/sms') }}/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
@endsection

@section('main-content')
  <div class="container-fluid">
<div class="block-header">

</div>

<!-- Vertical Layout -->
<div class="row clearfix">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="card">
<div class="header">

</div>
<div class="body">
<form action="{{ route('admin.subtype.update',$subtypeform->id) }}" method="POST" name="editForm">
	@csrf
	 @method('put')
	<div class="row clearfix">
     <div class="col-sm-6">
        <select name="type_id" class="form-control show-tick">
            @foreach($subtypes as $subtype)
            <option value="{{ $subtype->id }}">{{ $subtype->type }}</option>
            @endforeach
        </select>
    </div>
    <div class="col-sm-6">
    <label for="email_address">SubType</label>
    <div class="form-group">
        <div class="form-line">
           <input type="text" name="subtype" id="subtype" value="{{ $subtypeform->subtype }}" class="form-control">
        </div>
    </div>
    </div>
  </div>
     <a href="{{ route('admin.subtype.index') }}" class="btn bg-amber btn-lg waves-effect">
        <i class="material-icons">arrow_back</i>
       <span>Back</span>
     </a>
     <button type="submit" class="btn bg-pink btn-lg waves-effect">
        <i class="material-icons">save</i>
       <span>Update</span>
    </button>
     <button type="submit" class="btn bg-blue btn-lg waves-effect">
        <i class="material-icons">clear</i>
       <span>Clear</span>
    </button>
</form>
</div>
<script type="text/javascript">
	document.forms['editForm'].elements['type_id'].value='{{ $subtypeform->type }}';
</script>
</div>
</div>
</div>
<!-- #END# Vertical Layout -->
</div>
@endsection

@section('js')
<!-- Custom Js -->
<script src="{{ asset('assets/sms') }}/js/pages/forms/basic-form-elements.js"></script>
@endsection

resources/views/admin/subtype/index.blade.php
@extends('sms.backend.app')

@section('sms-title')
All Student | Admission Form Data
@endsection

@section('css')

    <!-- JQuery DataTable Css -->
    <link href="{{ asset('assets/sms') }}/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">

@endsection

@section('main-content')
  <div class="container-fluid">
<div class="block-header">
   <a href="{{ route('admin.subtype.create') }}" class="btn btn-warning btn-lg waves-effect">
         <i class="material-icons">create</i>
         <span>Create</span>
    </a>
</div>
<!-- Exportable Table -->
<div class="row clearfix">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="card">
<div class="header">
<button class="btn bg-purple btn-lg waves-effect" type="button">All Types <span class="badge">{{ $subtype->count() }}</span></button>
</div>
<div class="body">
<div class="table-responsive">
<table class="table table-bordered table-striped table-hover dataTable js-exportable">
<thead>
     <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Sub Type</th>
        <th>created_at</th>
        <th>updated_at</th>
        <th>Action</th>
    </tr>
</thead>
<tfoot>
     <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Sub Type</th>
        <th>created_at</th>
        <th>updated_at</th>
        <th>Action</th>
    </tr>
</tfoot>
<tbody>
@foreach($subtypes as $key=>$subtype)
<tr>
    <td>{{ $key + 1 }}</td>
    <td>{{ $subtype->type }}</td>
    <td>{{ $subtype->subtype }}</td>
    <td>{{ $subtype->created_at }}</td>
    <td>{{ $subtype->updated_at }}</td>
    <td>
     <a class="btn btn-primary" href=""><i class="material-icons">remove_red_eye</i></a>
     <a class="btn btn-success" href="{{ route('admin.subtype.edit', $subtype->id) }}"><i class="material-icons">edit</i></a> 
     <button class="btn btn-danger waves-effect" type="button" onclick="deleteSubType({{ $subtype->id }})">
        <i class="material-icons">delete</i>
    </button>
    <form id="delete-form-{{ $subtype->id }}" action="{{ route('admin.subtype.destroy',$subtype->id) }}" method="POST" style="display: none;">
        @csrf
          @method('DELETE')
    </form>
        
    </td>
</tr>
@endforeach
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<!-- #END# Exportable Table -->
        </div>
@endsection

@section('js')

    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

    <script src="{{ asset('assets/sms') }}/js/pages/tables/jquery-datatable.js"></script>
    <script src="{{ asset('js/sweetalert2.all.js') }}"></script>
     <!--<script src="https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>-->
     <script type="text/javascript">
        function deleteSubType(id) {
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false,
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-'+id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === swal.DismissReason.cancel
                ) {
                    swal(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                    )
                }
            })
        }
    </script>
@endsection