routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*admin route*/

Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');
Route::resource('type','TypeController');
Route::resource('subtype','SubTypeController');
Route::resource('student','StudentController');
Route::resource('parent','ParentController');
Route::resource('teacher','TeacherController');
Route::resource('staff','StaffController');
Route::resource('class','ClassController');
Route::resource('classroutine','ClassRoutineController');
Route::resource('exam','ExamController');
Route::resource('examschedule','StExamScheduleController');
Route::resource('subject','SubjectController');
Route::resource('expense','ExpenseController');
Route::resource('hostel','HostelController');
Route::resource('transport','TransportController');
Route::resource('message','MessageController');
Route::resource('notice','NoticeController');
Route::resource('attendance','AttendanceController');
});

/*author route*/

Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'author'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});

/*teacher route*/

Route::group(['as'=>'teacher.','prefix'=>'teacher','namespace'=>'teacher'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});

/*student route*/

Route::group(['as'=>'student.','prefix'=>'student','namespace'=>'student'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});


/*parent route*/

Route::group(['as'=>'parent.','prefix'=>'parent','namespace'=>'parent'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});


/*staff route*/

Route::group(['as'=>'staff.','prefix'=>'staff','namespace'=>'staff'], function(){

Route::get('dashboard','DashboardController@index')->name('dashboard');

});

app/Http/Controllers/Admin/StudentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Support\Str;
use Illuminate\Support\Arr;
use DB;
use App\Admin\StudentForm;
use App\Admin\TypeForm;
use App\Admin\SubTypeForm;
use App\Admin\ParentForm;
use Brian2694\Toastr\Facades\Toastr;

class StudentController extends Controller
{
    public function index()
    {
        $students = DB::table('student_forms')
                  ->join('parent_forms','student_forms.parent_id','=','parent_forms.id')
                  ->join('type_forms','student_forms.type_id','=','type_forms.id')
                  ->join('sub_type_forms','student_forms.subtype_id','=','sub_type_forms.id')
                  ->select('student_forms.*','parent_forms.fname as first_name','parent_forms.lname as last_name','parent_forms.address as addresses','type_forms.type','sub_type_forms.subtype')
                  ->get();
            
         return view('admin.student.index',compact('students'));         

    }

    public function create()
    {
        $types = TypeForm::select('id','type')->get();
        $parents = ParentForm::select('id','fname','lname')->get();
        $subtypes = SubTypeForm::select('id','subtype')->get();
        return view('admin.student.create',compact('types','subtypes','parents'));
    }

    public function store(Request $request)
    {
        $this->validate($request,[
         'fname' => 'required' , 'lname' => 'required', 'dob' => 'required', 'roll' => 'required', 'email' => 'required', 'phone' => 'required', 'bio' => 'required', 'image' => 'required|mimes:jpeg,jpg,bmp,png'
        ]);

          $image = $request->file('image');
        //$slug = str_slug($request->title);
        if (isset($image))
        {
            $currentDate = Carbon::now()->toDateString();
            $imagename = $currentDate .'-'. uniqid() .'.'. $image->getClientOriginalExtension();
            if (!file_exists('uploads/studentimages'))
            {
                mkdir('uploads/studentimages', 0777 , true);
            }
            $image->move('uploads/studentimages',$imagename);
        }else {
            $imagename = 'dafault.png';
        }
        $type_id = TypeForm::WHERE('id',$request->Class)->select('id')->first();
        
        $studentform = new StudentForm();
        $studentform->type_id = $type_id->id;
        $studentform->subtype_id = $request->Class;
        $studentform->parent_id = $request->parent_id;
        $studentform->fname = $request->fname;
        $studentform->lname = $request->lname;
        $studentform->dob = $request->dob;
        $studentform->roll = $request->roll;
        $studentform->email = $request->email;
        $studentform->phone = $request->phone;
        $studentform->bio = $request->bio;
        $studentform->image = $imagename;
        $studentform->save();
        Toastr::success('Student Data Successfully Created!! : ', 'success');
        return redirect()->route('admin.student.create');

    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {

    }

    public function update(Request $request, $id)
    {

    }

    public function destroy($id)
    {

    }
}

app/Http/Controllers/Student/DashboardController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(){

    	return view('sms.backend.home.index');
    }
}

resources/views/admin/student/create.blade.php
@extends('sms.backend.app')

@section('sms-title')
Create Student | Admission Form Data
@endsection

@section('css')
<!-- Bootstrap Select Css -->
<link href="{{ asset('assets/sms') }}/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
<!-- Multi Select Css -->
<link href="{{ asset('assets/sms') }}/plugins/multi-select/css/multi-select.css" rel="stylesheet">
<!-- Bootstrap Tagsinput Css -->
<link href="{{ asset('assets/sms') }}/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css" rel="stylesheet">
<!-- Bootstrap Select Css -->
<link href="{{ asset('assets/sms') }}/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />

@endsection

@section('main-content')
  <div class="container-fluid">
<div class="block-header">

</div>

<!-- Vertical Layout -->
<div class="row clearfix">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="card">
<div class="header">

</div>
<div class="body">
  <form action="{{ route('admin.student.store') }}" method="post" enctype="multipart/form-data">
    	@csrf

    <!--start row 1-->
    <div class="row clearfix">
      <div class="col-md-6"> 
        <div class="input-group input-group-lg">
          <span class="input-group-addon"><i class="material-icons">person</i></span>
          <div class="form-line">
            <input type="text" name="fname" id="fname" class="form-control" placeholder="Enter First Name..">
          </div>
        </div>
      </div>
       <div class="col-md-6"> 
        <div class="input-group input-group-lg">
          <span class="input-group-addon"><i class="material-icons">person_pin_circle</i></span>
          <div class="form-line">
            <input type="text" name="lname" id="lname" class="form-control" placeholder="Enter Last Name..">
          </div>
        </div>
      </div>
    </div>   
   <!--end row 1-->   

    <!--start row 2-->
    <div class="row clearfix">
      <div class="col-md-6"> 
        <div class="input-group input-group-lg">
          <span class="input-group-addon"><i class="material-icons">date_range</i></span>
          <div class="form-line">
            <input type="date" name="dob" id="dob" class="form-control" placeholder="Ex: 30/07/2016">
          </div>
        </div>
      </div>
       <div class="col-md-6"> 
        <div class="input-group input-group-lg">
          <span class="input-group-addon"><i class="material-icons">grain</i></span>
          <div class="form-line">
            <input type="text" name="roll" id="roll" class="form-control" placeholder="Enter Roll..">
          </div>
        </div>
      </div>
    </div>   
   <!--end row 2--> 

    <!--start row 2-->
    <div class="row clearfix">
      @foreach($types as $typeform)
       <div class="col-md-6">
      <select name="{{ $typeform->type }}" class="form-control show-tick">
            <b><option>-- Select {{ $typeform->type}} --</option></b>
               @foreach($subtypes as $subtypeform)
                 @if($typeform->id == $subtypeform->id)
            <option value="{{ $subtypeform->id }}">{{ $subtypeform->subtype }}</option>
                @endif
              @endforeach   
        </select>
      </div>
      @endforeach  
    </div> 
   <!--end row 2--> 
    <!--start row 2-->
    <div class="row clearfix">
       <div class="col-md-6">
      <select name="parent_id" class="form-control show-tick">
            <b><option>-- Select Parents --</option></b>
               @foreach($parents as $parent)
            <option value="{{ $parent->id }}">{{ $parent->fname ." ". $parent->lname }}</option>
              @endforeach   
        </select>
      </div>
    </div> 
   <!--end row 2-->
   <!--start row 3-->
    <div class="row clearfix">
      <div class="col-md-6"> 
        <div class="input-group input-group-lg">
          <span class="input-group-addon"><i class="material-icons">email</i></span>
          <div class="form-line">
            <input type="email" name="email" id="email" class="form-control" placeholder="Enter Email..">
          </div>
        </div>
      </div>
       <div class="col-md-6"> 
        <div class="input-group input-group-lg">
          <span class="input-group-addon"><i class="material-icons">call</i></span>
          <div class="form-line">
            <input type="text" name="phone" id="phone" class="form-control" placeholder="Enter Phone Number..">
          </div>
        </div>
      </div>
    </div>   
   <!--end row 3-->

    <!--start row 4-->
    <div class="row clearfix">
      <div class="col-md-6"> 
        <div class="input-group input-group-lg">
         <span class="input-group-addon"><i class="material-icons">local_florist</i></span>
          <div class="form-line">
           <textarea rows="5" cols="6" name="bio" id="bio" class="form-control" placeholder="Enter Shot Biography.."></textarea>
          </div>
        </div>
       </div>
       <div class="col-md-6"> 
        <div class="input-group input-group-lg">
          <div class="drag-icon-cph">
         <h1 class="input-group-addon"><i class="material-icons">touch_app</i></h1>
          </div>
          <div class="fallback">
           <input type="file" name="image" id="image" multiple/></textarea>
          </div>
        </div>
       </div>
    </div>       
   <!--end row 4-->   

    <div class="row">
      <div class="col-md-4">
    <a href="{{ route('admin.student.index') }}" class="btn bg-amber btn-lg btn-block waves-effect">
        <i class="material-icons">arrow_back</i>
       <span>Back</span>
     </a> 
      </div>
    <div class="col-md-4">
    <button type="submit" class="btn bg-pink btn-lg btn-block waves-effect">
        <i class="material-icons">save</i>
       <span>Save</span>
    </button>  
    </div>
    <div class="col-md-4">
    <button type="submit" class="btn bg-blue btn-lg btn-block waves-effect">
        <i class="material-icons">clear</i>
       <span>Clear</span>
    </button>
    </div>
    </div>

    </form>
</div>
</div>
</div>
</div>
<!-- #END# Vertical Layout -->
</div>
@endsection

@section('js')
<!-- Custom Js -->
<script src="{{ asset('assets/sms') }}/js/pages/forms/basic-form-elements.js"></script>
<!-- Select Plugin Js -->
<script src="{{ asset('assets/sms') }}/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<!-- Multi Select Plugin Js -->
<script src="{{ asset('assets/sms') }}/plugins/multi-select/js/jquery.multi-select.js"></script>
<!-- Bootstrap Tags Input Plugin Js -->
<script src="{{ asset('assets/sms') }}/plugins/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
<!-- Custom Js -->
<script src="{{ asset('assets/sms') }}/js/pages/forms/advanced-form-elements.js"></script>
<!-- Input Mask Plugin Js -->
<script src="{{ asset('assets/sms') }}/plugins/jquery-inputmask/jquery.inputmask.bundle.js"></script>
@endsection

resources/views/admin/student/edit.blade.php
@extends('sms.backend.app')

@section('sms-title')
Create Student | Admission Form Data
@endsection

@section('css')

    <!-- JQuery DataTable Css -->
    <link href="{{ asset('assets/sms') }}/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">

@endsection

@section('main-content')
  <div class="container-fluid">
<div class="block-header">

</div>

<!-- Vertical Layout -->
<div class="row clearfix">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="card">
<div class="header">

</div>
<div class="body">
<form method="POST" action="{{ route('admin.type.update',$type->id) }}">
	@csrf
	  @method('put')
    <label for="email_address">Type</label>
    <div class="form-group">
        <div class="form-line">
           <input type="text" name="type" id="type" value="{{ $type->type }}" class="form-control" placeholder="Enter Type">
        </div>
    </div>
     <a href="{{ route('admin.type.index') }}" class="btn bg-amber btn-lg waves-effect">
        <i class="material-icons">arrow_back</i>
       <span>Back</span>
     </a>
     <button type="submit" class="btn bg-pink btn-lg waves-effect">
        <i class="material-icons">save</i>
       <span>Update</span>
    </button>
     <button type="submit" class="btn bg-blue btn-lg waves-effect">
        <i class="material-icons">clear</i>
       <span>Clear</span>
    </button>
</form>
</div>
</div>
</div>
</div>
<!-- #END# Vertical Layout -->
</div>
@endsection

@section('js')

    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

    <script src="{{ asset('assets/sms') }}/js/pages/tables/jquery-datatable.js"></script>
@endsection

resources/views/admin/student/index.blade.php
@extends('sms.backend.app')

@section('sms-title')
All Student | Admission Form Data
@endsection

@section('css')

    <!-- JQuery DataTable Css -->
    <link href="{{ asset('assets/sms') }}/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">

@endsection

@section('main-content')
  <div class="container-fluid">
<div class="block-header">
   <a href="{{ route('admin.student.create') }}" class="btn btn-warning btn-lg waves-effect">
         <i class="material-icons">create</i>
         <span>Create</span>
    </a>
</div>
<!-- Exportable Table -->
<div class="row clearfix">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="card">
<div class="header">
<button class="btn bg-purple btn-lg waves-effect" type="button">All Students <span class="badge">{{ $students->count() }}</span></button>
</div>
<div class="body">
<div class="table-responsive">
<table class="table table-bordered table-striped table-hover dataTable js-exportable">
<thead>
    <tr>
        <th>ID</th>
        <th>Photo</th>
        <th>Full Name</th>
        <th>Parents</th>
        <th>Address</th>
        <th>Action</th>
    </tr>
</thead>
<tfoot>
     <tr>
        <th>ID</th>
        <th>Photo</th>
        <th>Full Name</th>
        <th>Parents</th>
        <th>Address</th>
        <th>Action</th>
    </tr>
</tfoot>
<tbody>
@foreach($students as $key=>$student)
<tr>
    <td>{{ $key + 1 }}</td>
    <td><img src="{{ asset('uploads/studentimages/'.$student->image) }}" width="60" height="60"></td>
    <td>{{ $student->fname ." ". $student->lname }}</td>
    <td>{{ $student->first_name ." ". $student->last_name }}</td>
    <td>{{ $student->addresses }}</td>
    <td>
     <a class="btn btn-primary" href=""><i class="material-icons">remove_red_eye</i></a>
     <a class="btn btn-success" href="{{ route('admin.student.edit', $student->id) }}"><i class="material-icons">edit</i></a> 
     <button class="btn btn-danger waves-effect" type="button" onclick="deleteType({{ $student->id }})">
        <i class="material-icons">delete</i>
    </button>
    <form id="delete-form-{{ $student->id }}" action="{{ route('admin.student.destroy',$student->id) }}" method="POST" style="display: none;">
        @csrf
          @method('DELETE')
    </form>
        
    </td>
</tr>
@endforeach
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<!-- #END# Exportable Table -->
        </div>
@endsection

@section('js')

    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="{{ asset('assets/sms') }}/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>

    <script src="{{ asset('assets/sms') }}/js/pages/tables/jquery-datatable.js"></script>
    <script src="{{ asset('js/sweetalert2.all.js') }}"></script>
     <!--<script src="https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>-->
     <script type="text/javascript">
        function deleteType(id) {
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false,
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-'+id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === swal.DismissReason.cancel
                ) {
                    swal(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                    )
                }
            })
        }
    </script>
@endsection